# ---------- Base ----------
FROM node:22-alpine AS base
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

# ---------- Dependencies ----------
FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# ---------- Build ----------
FROM base AS build
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ARG JWT_SECRET
ARG ENCRYPTION_KEY
ARG NEXT_PUBLIC_POST_TRIGGER_WEBHOOK
ARG NEXT_PUBLIC_VIDEO_TRIGGER_WEBHOOK
ARG NEXT_PUBLIC_SEARCH_IDEAS_WEBHOOK
ARG NEXT_PUBLIC_ENGAGEMENT_TRACKER_WEBHOOK
ARG NEXT_PUBLIC_REMOVE_POST_WEBHOOK
ARG NEXT_PUBLIC_EDIT_CONTENT_WEBHOOK
ARG NEXT_PUBLIC_EDIT_MEDIA_WEBHOOK
ARG NEXT_PUBLIC_AUTO_POST_WEBHOOK
ARG NEXT_PUBLIC_POST_NOW_WEBHOOK
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=$NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ENV JWT_SECRET=$JWT_SECRET
ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV NEXT_PUBLIC_POST_TRIGGER_WEBHOOK=$NEXT_PUBLIC_POST_TRIGGER_WEBHOOK
ENV NEXT_PUBLIC_VIDEO_TRIGGER_WEBHOOK=$NEXT_PUBLIC_VIDEO_TRIGGER_WEBHOOK
ENV NEXT_PUBLIC_SEARCH_IDEAS_WEBHOOK=$NEXT_PUBLIC_SEARCH_IDEAS_WEBHOOK
ENV NEXT_PUBLIC_ENGAGEMENT_TRACKER_WEBHOOK=$NEXT_PUBLIC_ENGAGEMENT_TRACKER_WEBHOOK
ENV NEXT_PUBLIC_REMOVE_POST_WEBHOOK=$NEXT_PUBLIC_REMOVE_POST_WEBHOOK
ENV NEXT_PUBLIC_EDIT_CONTENT_WEBHOOK=$NEXT_PUBLIC_EDIT_CONTENT_WEBHOOK
ENV NEXT_PUBLIC_EDIT_MEDIA_WEBHOOK=$NEXT_PUBLIC_EDIT_MEDIA_WEBHOOK
ENV NEXT_PUBLIC_AUTO_POST_WEBHOOK=$NEXT_PUBLIC_AUTO_POST_WEBHOOK
ENV NEXT_PUBLIC_POST_NOW_WEBHOOK=$NEXT_PUBLIC_POST_NOW_WEBHOOK
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

# ---------- Runtime ----------
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# ?? B?T BU?C C�I PNPM L?I
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/next.config.* ./

EXPOSE 3007

CMD ["pnpm", "start"]