import type { Project, Schedule, ContentItem } from "./types"

export const projects: Project[] = [
  { id: "1", name: "SUPER APP", color: "#3b82f6" },
  { id: "2", name: "HỆ THỐNG ECOOP", color: "#22c55e" },
  { id: "3", name: "APEC BCI", color: "#eab308" },
  { id: "4", name: "APEC TECH", color: "#f97316" },
  { id: "5", name: "LIFE CARE", color: "#8b5cf6" },
]

export const schedules: Schedule[] = [
  {
    id: "1",
    projectId: "1",
    projectName: "SUPER APP",
    platform: "Facebook Post",
    frequency: "10 phút/lần",
    postingDays: "Mỗi ngày",
    postingTime: "12:30",
  },
  {
    id: "2",
    projectId: "1",
    projectName: "SUPER APP",
    platform: "Facebook Reels",
    frequency: "Tuần",
    postingDays: "Thứ 2, Thứ 6",
    postingTime: "08:00",
  },
  {
    id: "3",
    projectId: "1",
    projectName: "SUPER APP",
    platform: "Youtube Shorts",
    frequency: "Ngày",
    postingDays: "Mỗi ngày",
    postingTime: "19:30",
  },
  {
    id: "4",
    projectId: "2",
    projectName: "HỆ THỐNG ECOOP",
    platform: "Facebook Post",
    frequency: "10 phút/lần",
    postingDays: "Mỗi ngày",
    postingTime: "11:00",
  },
  {
    id: "5",
    projectId: "2",
    projectName: "HỆ THỐNG ECOOP",
    platform: "Facebook Reels",
    frequency: "Tháng",
    postingDays: "Ngày 5, ngày 20",
    postingTime: "07:30",
  },
  {
    id: "6",
    projectId: "2",
    projectName: "HỆ THỐNG ECOOP",
    platform: "Youtube Shorts",
    frequency: "Ngày",
    postingDays: "Mỗi ngày",
    postingTime: "18:00",
  },
  {
    id: "7",
    projectId: "3",
    projectName: "APEC BCI",
    platform: "Facebook Post",
    frequency: "Tuần",
    postingDays: "Thứ 2, Thứ 5",
    postingTime: "21:00",
  },
  {
    id: "8",
    projectId: "3",
    projectName: "APEC BCI",
    platform: "Facebook Reels",
    frequency: "Tuần",
    postingDays: "Thứ 3, Thứ 7",
    postingTime: "09:00",
  },
  {
    id: "9",
    projectId: "4",
    projectName: "APEC TECH",
    platform: "Facebook Post",
    frequency: "Tháng",
    postingDays: "Ngày 10, ngày 25, ngày 27",
    postingTime: "11:00",
  },
  {
    id: "10",
    projectId: "4",
    projectName: "APEC TECH",
    platform: "Facebook Reels",
    frequency: "Tuần",
    postingDays: "Thứ 4, Chủ nhật",
    postingTime: "13:00",
  },
  {
    id: "11",
    projectId: "4",
    projectName: "APEC TECH",
    platform: "Youtube Shorts",
    frequency: "Tuần",
    postingDays: "Thứ 3, Thứ 6",
    postingTime: "20:30",
  },
  {
    id: "12",
    projectId: "5",
    projectName: "LIFE CARE",
    platform: "Facebook Post",
    frequency: "Tuần",
    postingDays: "Thứ 3, Thứ 6",
    postingTime: "14:00",
  },
  {
    id: "13",
    projectId: "5",
    projectName: "LIFE CARE",
    platform: "Facebook Reels",
    frequency: "Tháng",
    postingDays: "Ngày 8, ngày 22",
    postingTime: "07:00",
  },
  {
    id: "14",
    projectId: "5",
    projectName: "LIFE CARE",
    platform: "Youtube Shorts",
    frequency: "3 ngày/lần",
    postingDays: "Ngày lẻ",
    postingTime: "07:00",
  },
]

export const contentItems: ContentItem[] = [
  {
    id: "1",
    status: "cho_duyet",
    idea: "Nước uống",
    projectId: "5",
    projectName: "LIFE CARE",
    platform: "Facebook Reels",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "",
    targetAudience: "Age: 18-45, male/female, students/office workers/young professionals",
    researchNotes: "Competitive analysis of existing e-commerce apps (e.g. Shopee, Lazada)",
    expectedPostDate: "2025-11-28",
    postingTime: "12:00",
    script: [
      {
        scene: 1,
        description: "Cảnh mở đầu với ly nước tươi mát",
        dialogue: "Bạn có biết uống nước đúng cách giúp tăng năng lượng?",
      },
      {
        scene: 2,
        description: "Hiển thị sản phẩm LIFE CARE",
        dialogue: "LIFE CARE mang đến giải pháp nước uống hoàn hảo cho bạn!",
      },
    ],
    caption: "Uống nước đúng cách - Bí quyết sức khỏe mỗi ngày! #LIFECARE #SucKhoe",
    callToAction: "Đặt hàng ngay hôm nay để nhận ưu đãi đặc biệt!",
  },
  {
    id: "2",
    status: "cho_duyet",
    idea: "App thương mại điện tử",
    projectId: "1",
    projectName: "SUPER APP",
    platform: "Facebook Reels",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "App thương mại điện tử",
    targetAudience: "Age: 18-45, male/female, students/office workers/young professionals",
    researchNotes: "Competitive analysis of existing e-commerce apps (e.g. Shopee, Lazada)",
    expectedPostDate: "",
    postingTime: "",
  },
  {
    id: "3",
    status: "da_dang_thanh_cong",
    idea: "Xe bán hàng lưu động",
    projectId: "2",
    projectName: "HỆ THỐNG ECOOP",
    platform: "Facebook Reels",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "Xe bán hàng lưu động",
    targetAudience: "Age: 18-45, Gender: All, Occupation: Office workers, students",
    researchNotes: "Research current trends in mobile vending (food truck, coffee cart)",
    expectedPostDate: "2025-12-02",
    postingTime: "19:00",
    script: [
      { scene: 1, description: "Cảnh xe bán hàng ECOOP", dialogue: "Khám phá mô hình kinh doanh lưu động cùng ECOOP!" },
    ],
    caption: "Xe bán hàng lưu động ECOOP - Giải pháp kinh doanh linh hoạt! #ECOOP #KinhDoanh",
    callToAction: "Liên hệ ngay để được tư vấn!",
  },
  {
    id: "4",
    status: "cho_duyet",
    idea: "Vật lý trị liệu",
    projectId: "5",
    projectName: "LIFE CARE",
    platform: "Facebook Reels",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "Vật lý trị liệu",
    targetAudience: "Age 30-65+, individuals recovering from injuries/surgeries",
    researchNotes: "Common conditions treated by physical therapy, benefits",
    expectedPostDate: "2025-12-01",
    postingTime: "19:00",
  },
  {
    id: "5",
    status: "da_dang_thanh_cong",
    idea: "Xe bán hàng lưu động",
    projectId: "2",
    projectName: "HỆ THỐNG ECOOP",
    platform: "Youtube Shorts",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "Xe bán hàng lưu động",
    targetAudience: "Age: 18-45, Gender: All, Occupation: Office workers, students",
    researchNotes: "Research current trends in mobile vending (food truck, coffee cart)",
    expectedPostDate: "2025-11-30",
    postingTime: "10:00",
    script: [
      { scene: 1, description: "Giới thiệu xe bán hàng", dialogue: "Bạn muốn khởi nghiệp với vốn nhỏ? Xem ngay!" },
    ],
    caption: "Khởi nghiệp cùng ECOOP! #ECOOP #KhoiNghiep",
    callToAction: "Đăng ký ngay để nhận ưu đãi!",
  },
  {
    id: "6",
    status: "cho_duyet",
    idea: "App thương mại điện tử",
    projectId: "1",
    projectName: "SUPER APP",
    platform: "Youtube Shorts",
    existingVideoLink: "",
    videoDuration: 5,
    imageLink: "",
    topic: "App thương mại điện tử",
    targetAudience: "Age: 18-45, male/female, students/office workers/young professionals",
    researchNotes: "Competitive analysis of existing e-commerce apps",
    expectedPostDate: "2025-11-27",
    postingTime: "14:00",
  },
]
